# Live config reload (changes require restart)
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.8
blur = true
decorations = "Full"
#option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 2
y = 2

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 500
unfocused_hollow = false
thickness = 0.2

[font]
size = 14

#[shell]
#program = "/usr/bin/zsh"
#args = ["-l", "-c", "zellij attach --index 0 || zellij"]

[scrolling]
history = 10000
multiplier = 3


[keyboard]
bindings = [
    # <Ctrl>-<Shift>-C for copy
    { key = "C", mods = "CONTROL|SHIFT", action = "Copy"},

    # <Ctrl>-<Shift>-V for paste
    { key = "V", mods = "CONTROL|SHIFT", action = "Paste"},

    # ⌘ + enter puts window in full screen
    { key = "Enter", mods = "Command", action = "ToggleFullscreen"},

    # opt + right and left jump between words
    { key = "Right", mods = "Shift", chars = "\u001BF" },
    { key = "Left",  mods = "Shift", chars = "\u001BB" },

    # For Tmux
    # ⌘ + d adds a pane to the right (splits window vertically)
    #{ key = "D",  mods = "Command", chars = "\u0002%" },
    # ⌘ + ⇧ + d adds a pane below (splits window horizontally)
    #{ key = "D",  mods = "Command|Shift", chars = "\u0002\"" },
    # ⌘ + w prompts you to close the pane, "y" to confirm
    #{ key = "W",  mods = "Command", chars = "\u0002x" },
    # ⌘ + arrows are for directional navigation around the panes
    # move down a pane
    #{ key = "Down", mods = "Command", chars = "\u0002\u001b[B" },
    # move up a pane
    #{ key = "Up", mods = "Command", chars = "\u0002\u001b[A" },
    # move left a pane
    #{ key = "Left", mods = "Command", chars = "\u0002\u001b[D" }
    # move right a pane
    #{ key = "Right", mods = "Command", chars = "\u0002\u001b[C" },
    # ⌘ + ⇧ + enter maximizes the pane within the alacritty window
    #{ key = "Enter", mods = "Command|Shift", chars = "\u0002z" },


  { key = "V", mods = "Control|Option", action = "PasteSelection" },

  { key = "Key0",   mods = "Control", action = "ResetFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus",  mods = "Control", action = "DecreaseFontSize" },
  { key = "Return", mods = "Alt", action = "ToggleFullScreen" },

  # Spawn new instance in same directory
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },


  { key = "PageUp", mods = "Control|Shift", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Control|Shift", action = "ScrollPageDown" },
  { key = "Home", mods = "Control|Shift", action = "ScrollToTop" },
  { key = "End", mods = "Control|Shift", action = "ScrollToBottom" },

  { key = "F", mods = "Control|Shift", mode = "Search", action = "SearchForward" },
  { key = "B", mods = "Control|Shift", mode = "Search", action = "SearchBackward" },

  # Delete Line
  # { key =dddddd "Back",  mods = "Command", chars = "\u0015" },

  # Home
  # { key = "Left", mods = "Command", chars = "\u1b0H", mode = "AppCursor" },

  # End
  # { key = "Right", mods = "Command", chars = "\u1bOF", mode = "AppCursor" }

  # Delete
  # { key = "Del",  mods = "Control", chars = "\u7f" },

]


[mouse]
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  #double_click = { threshold = 300 }
  #triple_click = { threshold = 300 }

  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing = false
  bindings = [
      { mouse = "Right", mods = "Control", action = "PasteSelection" }
  ]

# https://wiki.archlinux.org/title/Alacritty#Hints


[selection]
# This string contains all characters that are used as separators for
# "semantic words" in Alacritty.
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# When set to `true`, selected text will be copied to the primary clipboard.
save_to_clipboard = true